/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package scrabble_challenge;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ScrabbleTest {
    @Test void returnsCorrectWord() {
        Scrabble classUnderTest = new Scrabble("Hi");
        assertEquals(classUnderTest.getWord(), "hi");
    }
    @Test void returnsZeroForEmptyWords() {
        Scrabble classUnderTest = new Scrabble("");
        assertEquals(classUnderTest.getWord(), "");
        assertEquals(classUnderTest.wordScore(), 0);
    }
    @Test void returnsZeroForWhitespace() {
        Scrabble classUnderTest = new Scrabble(" \t\n");
        assertEquals(classUnderTest.getWord(), " \t\n");
        assertEquals(classUnderTest.wordScore(), 0);
    }
    @Test void returnsZeroForNull() {
        Scrabble classUnderTest = new Scrabble(null);
        assertEquals(classUnderTest.wordScore(), 0);
    }
    @Test void scoresLetterACorrectly() {
        Scrabble classUnderTest = new Scrabble("a");
        assertEquals(classUnderTest.wordScore(), 1);
    }
    @Test void scoresLetterFCorrectly() {
        Scrabble classUnderTest = new Scrabble("f");
        assertEquals(classUnderTest.wordScore(), 4);
    }
    @Test void scoresStreetCorrectly() {
        Scrabble classUnderTest = new Scrabble("street");
        assertEquals(classUnderTest.wordScore(), 6);
    }
    @Test void scoresQuirkyCorrectly() {
        Scrabble classUnderTest = new Scrabble("quirky");
        assertEquals(classUnderTest.wordScore(), 22);
    }
    @Test void scoresACaseInsensitiveWord() {
        Scrabble classUnderTest = new Scrabble("OXYPHENBUTAZONE");
        assertEquals(classUnderTest.wordScore(), 41);
    }
}
